# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJ8SboYpteqOjOC3tqqgc56A3bgTDRry
"""

print("hello")

index = [
    ["P0", 3, 1],
    ["P1", 5, 3],
    ["P2", 2, 2],
    ["P3", 1, 2],
    ["P4", 6, 3]
]

index.sort(key=lambda x: x[1])

current_time = 0

total_tat = 0
total_wt = 0

print("PID\tAT\tBT\tCT\tTAT\tWT")

for p in index:
    pid, at, bt = p

    if current_time < at:
        current_time = at

    current_time += bt
    ct = current_time

    tat = ct - at
    wt = tat - bt

    total_tat += tat
    total_wt += wt

    print(f"{pid}\t{at}\t{bt}\t{ct}\t{tat}\t{wt}")

avg_tat = total_tat / len(index)
avg_wt = total_wt / len(index)

print("\nAverage TAT =", round(avg_tat, 2))
print("Average WT =", round(avg_wt, 2))