# -*- coding: utf-8 -*-
"""ROUND ROBIN CPU Scheduling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PnLtFfRl5_cRrXEkoe4BPl-4Ih1kGIW
"""

processes = [
    ["P1", 0, 7],
    ["P2", 1, 4],
    ["P3", 2, 15],
    ["P4", 3, 11],
    ["P5", 4, 20],
    ["P6", 4, 9]
]



def fcfs(processes):
    procs = sorted(processes, key=lambda x: x[1])

    current_time = 0
    result = []

    for pid, at, bt in procs:

        if current_time < at:
            current_time = at

        ct = current_time + bt
        tat = ct - at
        wt = tat - bt

        result.append([pid, at, bt, ct, tat, wt])

        current_time = ct

    return result



def sjf_non_preemptive(processes):

    n = len(processes)
    is_done = [False] * n

    current_time = 0
    completed = 0
    result = []

    while completed != n:

        idx = -1
        min_bt = float('inf')

        for i in range(n):

            pid, at, bt = processes[i]

            if at <= current_time and not is_done[i]:

                if bt < min_bt:
                    min_bt = bt
                    idx = i


        if idx == -1:
            current_time += 1
            continue

        pid, at, bt = processes[idx]

        current_time += bt

        ct = current_time
        tat = ct - at
        wt = tat - bt

        result.append([pid, at, bt, ct, tat, wt])

        is_done[idx] = True
        completed += 1

    return result



def round_robin(processes, quantum):

    n = len(processes)

    procs = sorted(processes, key=lambda x: x[1])

    remaining_bt = [p[2] for p in procs]

    completion_time = [0] * n

    ready_queue = deque()

    current_time = 0
    i = 0

    while i < n or ready_queue:


        while i < n and procs[i][1] <= current_time:
            ready_queue.append(i)
            i += 1


        if not ready_queue:
            current_time = procs[i][1]
            continue


        idx = ready_queue.popleft()

        execution_time = min(quantum, remaining_bt[idx])

        current_time += execution_time

        remaining_bt[idx] -= execution_time

        while i < n and procs[i][1] <= current_time:
            ready_queue.append(i)
            i += 1


        if remaining_bt[idx] > 0:
            ready_queue.append(idx)

        else:
            completion_time[idx] = current_time

    result = []

    for i in range(n):

        pid, at, bt = procs[i]

        ct = completion_time[i]
        tat = ct - at
        wt = tat - bt

        result.append([pid, at, bt, ct, tat, wt])

    return result


def print_table(title, result):

    print("\n" + title)

    print(f"{'PID':<6}{'AT':<5}{'BT':<5}{'CT':<5}{'TAT':<6}{'WT':<5}")

    for r in sorted(result, key=lambda x: x[0]):

        pid, at, bt, ct, tat, wt = r

        print(f"{pid:<6}{at:<5}{bt:<5}{ct:<5}{tat:<6}{wt:<5}")

    avg_tat = sum(r[4] for r in result) / len(result)
    avg_wt = sum(r[5] for r in result) / len(result)

    print(f"Average TAT = {avg_tat:.2f}")
    print(f"Average WT  = {avg_wt:.2f}")

    return avg_tat, avg_wt


fcfs_result = fcfs(processes)

sjf_result = sjf_non_preemptive(processes)

quantum = 5
rr_result = round_robin(processes, quantum)



fcfs_tat, fcfs_wt = print_table(
    "FCFS Result",
    fcfs_result
)

sjf_tat, sjf_wt = print_table(
    "SJF Result",
    sjf_result
)

rr_tat, rr_wt = print_table(
    f"Round Robin Result (Quantum = {quantum})",
    rr_result
)



print("\n--- Comparison ---")

print(f"{'Metric':<20}{'FCFS':<10}{'SJF':<10}{'RR':<10}")

print(
    f"{'Avg TAT':<20}"
    f"{fcfs_tat:<10.2f}"
    f"{sjf_tat:<10.2f}"
    f"{rr_tat:<10.2f}"
)

print(
    f"{'Avg WT':<20}"
    f"{fcfs_wt:<10.2f}"
    f"{sjf_wt:<10.2f}"
    f"{rr_wt:<10.2f}"
)