# -*- coding: utf-8 -*-
"""Priority Scheduling non preemptive & preemptive Implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ol6ya9b14Ew7tlDHpeOjJJg7rrbNp_uv
"""

def priority_non_preemptive(processes):
    n = len(processes)
    completed = 0
    current_time = 0
    is_done = [False] * n
    result = []

    while completed != n:
        idx = -1
        best_priority = float('inf')

        for i in range(n):
            pid, at, bt, pr = processes[i]
            if at <= current_time and not is_done[i]:
                if pr < best_priority:
                    best_priority = pr
                    idx = i

        if idx == -1:
            current_time += 1
            continue

        pid, at, bt, pr = processes[idx]
        current_time += bt
        ct = current_time
        tat = ct - at
        wt = tat - bt

        result.append([pid, at, bt, pr, ct, tat, wt])
        is_done[idx] = True
        completed += 1

    return result


processes = [
    ["P1", 0, 3, 3],
    ["P2", 1, 4, 2],
    ["P3", 2, 6, 4],
    ["P4", 3, 4, 6],
    ["P5", 5, 2, 10]
]

result = priority_non_preemptive(processes)

result_sorted = sorted(result, key=lambda x: x[0])

print(f"{'Process':<8}{'AT':<5}{'BT':<5}{'Pr':<5}{'CT':<5}{'TAT':<5}{'WT':<5}")
for row in result_sorted:
    pid, at, bt, pr, ct, tat, wt = row
    print(f"{pid:<8}{at:<5}{bt:<5}{pr:<5}{ct:<5}{tat:<5}{wt:<5}")

avg_tat = sum(r[5] for r in result) / len(result)
avg_wt = sum(r[6] for r in result) / len(result)
print(f"\nAverage TAT = {avg_tat:.2f}")
print(f"Average WT = {avg_wt:.2f}")

def priority_preemptive(processes):
    n = len(processes)
    remaining_bt = [p[2] for p in processes]
    completed = 0
    current_time = 0
    is_done = [False] * n
    completion_time = [0] * n

    while completed != n:
        idx = -1
        best_priority = float('inf')

        for i in range(n):
            pid, at, bt, pr = processes[i]
            if at <= current_time and not is_done[i] and remaining_bt[i] > 0:
                if pr < best_priority:
                    best_priority = pr
                    idx = i

        if idx == -1:
            current_time += 1
            continue

        remaining_bt[idx] -= 1
        current_time += 1

        if remaining_bt[idx] == 0:
            is_done[idx] = True
            completed += 1
            completion_time[idx] = current_time

    result = []
    for i in range(n):
        pid, at, bt, pr = processes[i]
        ct = completion_time[i]
        tat = ct - at
        wt = tat - bt
        result.append([pid, at, bt, pr, ct, tat, wt])

    return result


processes = [
    ["P1", 0, 3, 3],
    ["P2", 1, 4, 2],
    ["P3", 2, 6, 4],
    ["P4", 3, 4, 6],
    ["P5", 5, 2, 10]
]

result = priority_preemptive(processes)

result_sorted = sorted(result, key=lambda x: x[0])

print(f"{'Process':<8}{'AT':<5}{'BT':<5}{'Pr':<5}{'CT':<5}{'TAT':<5}{'WT':<5}")
for row in result_sorted:
    pid, at, bt, pr, ct, tat, wt = row
    print(f"{pid:<8}{at:<5}{bt:<5}{pr:<5}{ct:<5}{tat:<5}{wt:<5}")

avg_tat = sum(r[5] for r in result) / len(result)
avg_wt = sum(r[6] for r in result) / len(result)
print(f"\nAverage TAT = {avg_tat:.2f}")
print(f"Average WT = {avg_wt:.2f}")