# -*- coding: utf-8 -*-
"""Sjf without comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8xZzbHCpn_IX03wdpbQ3cu0DIeeg79t
"""

def sjf_preemptive(processes, quantum):
    n = len(processes)
    remaining_bt = [p[2] for p in processes]
    completed = 0
    current_time = 0
    is_done = [False] * n
    completion_time = [0] * n

    while completed != n:
        idx = -1
        min_rt = float('inf')

        for i in range(n):
            pid, at, bt = processes[i]
            if at <= current_time and not is_done[i] and remaining_bt[i] > 0:
                if remaining_bt[i] < min_rt:
                    min_rt= remaining_bt[i]
                    idx = i

        if idx == -1:
            current_time += 1
            continue

        run_time = min(quantum, remaining_bt[idx])
        remaining_bt[idx] -= run_time
        current_time += run_time

        if remaining_bt[idx] == 0:
            is_done[idx] = True
            completed += 1
            completion_time[idx] = current_time

    result = []
    for i in range(n):
        pid,at,bt=processes[i]
        ct=completion_time[i]
        tat=ct-at
        wt=            tat-bt
        result.append([pid,at,bt,ct,tat,wt])

    return result


processes = [
    ["P1", 4, 2],
    ["P2", 2, 2],
    ["P3", 1, 3],
    ["P4", 0, 6],
    ["P5", 3, 1]
]

quantum = 2
result = sjf_preemptive(processes, quantum)

result_sorted = sorted(result, key=lambda x: x[0])

print(f"{'Process':<8}{'AT':<5}{'BT':<5}{'CT':<5}{'TAT':<5}{'WT':<5}")
for row in result_sorted:
    pid, at, bt, ct, tat, wt = row
    print(f"{pid:<8}{at:<5}{bt:<5}{ct:<5}{tat:<5}{wt:<5}")

avg_tat = sum(r[4] for r in result) / len(result)
avg_wt = sum(r[5] for r in result) / len(result)
print(f"\nAverage TAT = {avg_tat:.2f}")
print(f"Average WT = {avg_wt:.2f}")