# -*- coding: utf-8 -*-
"""sjf comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_bSGyTf7fK4rGRy5NNwt2h6c-tWQo-x
"""

index = [
    ["P0", 3, 3],
    ["P1", 2, 5],
    ["P2", 5, 4],
    ["P3", 1, 3],
    ["P4", 6, 2]
]

index.sort(key=lambda x: x[1])

current_time = 0

total_tat = 0
total_wt = 0

print("PID\tAT\tBT\tCT\tTAT\tWT")

for p in index:
    pid, at, bt = p

    if current_time < at:
        current_time = at

    current_time += bt
    ct = current_time

    tat = ct - at
    wt = tat - bt

    total_tat += tat
    total_wt += wt

    print(f"{pid}\t{at}\t{bt}\t{ct}\t{tat}\t{wt}")

avg_tat = total_tat / len(index)
avg_wt = total_wt / len(index)

print("\nAverage TAT =", round(avg_tat, 2))
print("Average WT =", round(avg_wt, 2))

def sjf_non_preemptive(processes):

    n = len(processes)
    completed = 0
    current_time = 0
    is_done = [False] * n
    result = []

    while completed != n:
        idx = -1
        min_bt = float('inf')

        for i in range(n):
            pid, at, bt = processes[i]
            if at <= current_time and not is_done[i]:
                if bt < min_bt:
                    min_bt = bt
                    idx = i
                if bt == min_bt and at < processes[idx][1]:
                    idx = i

        if idx == -1:

            current_time += 1
            continue

        pid, at, bt = processes[idx]
        current_time += bt
        ct = current_time
        tat = ct - at
        wt = tat - bt

        result.append([pid, at, bt, ct, tat, wt])
        is_done[idx] = True
        completed += 1

    return result



processes = [
    ["P1", 3, 3],
    ["P2", 2, 5],
    ["P3", 5, 4],
    ["P4", 1, 3],
    ["P5", 6, 2],
]

result = sjf_non_preemptive(processes)


result_sorted = sorted(result, key=lambda x: x[0])

print(f"{'Process':<8}{'AT':<5}{'BT':<5}{'CT':<5}{'TAT':<5}{'WT':<5}")
for row in result_sorted:
    pid, at, bt, ct, tat, wt = row
    print(f"{pid:<8}{at:<5}{bt:<5}{ct:<5}{tat:<5}{wt:<5}")

avg_tat = sum(r[4] for r in result) / len(result)
avg_wt = sum(r[5] for r in result) / len(result)
print(f"\nAverage TAT = {avg_tat:.2f}")
print(f"Average WT = {avg_wt:.2f}")

def fcfs(processes):
    procs = sorted(processes, key=lambda x: x[1])  # sort by AT
    time = 0
    result = []
    for pid, at, bt in procs:
        start = max(time, at)
        ct = start + bt
        tat = ct - at
        wt = tat - bt
        result.append([pid, at, bt, ct, tat, wt])
        time = ct
    return result


def sjf_non_preemptive(processes):
    n = len(processes)
    is_done = [False] * n
    current_time = 0
    completed = 0
    result = []

    while completed != n:
        idx = -1
        min_bt = float('inf')
        for i in range(n):
            pid, at, bt = processes[i]
            if at <= current_time and not is_done[i] and bt < min_bt:
                min_bt = bt
                idx = i
        if idx == -1:
            current_time += 1
            continue
        pid, at, bt = processes[idx]
        current_time += bt
        ct = current_time
        tat = ct - at
        wt = tat - bt
        result.append([pid, at, bt, ct, tat, wt])
        is_done[idx] = True
        completed += 1
    return result


def print_table(title, result):
    print(f"\n{title}")
    print(f"{'PID':<6}{'AT':<5}{'BT':<5}{'CT':<5}{'TAT':<5}{'WT':<5}")
    for r in sorted(result, key=lambda x: x[0]):
        print(f"{r[0]:<6}{r[1]:<5}{r[2]:<5}{r[3]:<5}{r[4]:<5}{r[5]:<5}")
    avg_tat = sum(r[4] for r in result) / len(result)
    avg_wt = sum(r[5] for r in result) / len(result)
    print(f"Average TAT = {avg_tat:.2f}, Average WT = {avg_wt:.2f}")
    return avg_tat, avg_wt


processes = [
    ["P1", 3, 3],
    ["P2", 2, 5],
    ["P3", 5, 4],
    ["P4", 1, 3],
    ["P5", 6, 2],
]

fcfs_result = fcfs(processes)
sjf_result = sjf_non_preemptive(processes)

fcfs_tat, fcfs_wt = print_table("FCFS Result", fcfs_result)
sjf_tat, sjf_wt = print_table("SJF Result", sjf_result)

print("\n--- Comparison ---")
print(f"{'Metric':<20}{'FCFS':<10}{'SJF':<10}")
print(f"{'Avg TAT':<20}{fcfs_tat:<10.2f}{sjf_tat:<10.2f}")
print(f"{'Avg WT':<20}{fcfs_wt:<10.2f}{sjf_wt:<10.2f}")